name: Main Config
version: 1.0.0
schema: v1
models:
  - name: Ollama Gemma
    provider: ollama
    model: gemma4:12b
    roles:
      - chat
      - edit
      - apply
      - autocomplete

  - name: Nomic Embed
    provider: ollama
    model: nomic-embed-text:latest
    roles:
      - embed
